### PR TITLE
Restructuring docs

### PR DESCRIPTION
**Pull request by IvanGrginovInf**
This PR is my take on the structure / layout of our docs. It completely changes the structure of main navigation and the flow of users, (hopefully) in the direction we talked about on our standup.

_**If you plan on testing this, i HIGHLY recommend checking out the branch locally and starting the docs, otherwise all these changes will make little sense.**_

Changelog
---
* Re-organised the layout of pages to better resemble other document sites
* Updated main site navigation to:
  * Getting Started
  * Docs
  * Guides
  * Storybook
  * Search input field
* Added homepage with a simple splash screen, buttons and some features
* Added `get-started` page, it's purpose to direct users to one of 4 things:
  * How to create a new theme
  * How to create a new plugin
  * How to integrate `libs` & `frontend-libs` into an existing projects
  * To docs
* Added `docs` landing page (_would benefit from a better design but we can work on it)_, it's purpose to direct users to one of 2 things:
  * `libs` docs
  * `frontend-libs` docs
* Added docs page for integrating `libs` & `frontend-libs` into an existing projects (more or less just directing users to each lib's installation section)
* Modified the styling of buttons to resemble Eightshift's buttons
* Removed facebook's Open Source Collective logo from footer
* Fixed some broken links
* Fixed some typos

This PR addresses #1 (although there's definitely room for improvement)

### CODE REVIEW

**Comment by dingo-d** [comment]
Love the structure, the only issue I have is the 100px border-radius on the cards and the huge 'pop up' effect on hover.
Just looks... well... kinda ugly :S

Maybe something less bordered with a less yellow background? Something like:

example

Make it as 'clean' as possible no need to go overboard with tons of different colors. Some inspiration:

https://dribbble.com/search/documentation

**Comment by iruzevic** [comment]
Awesome great work

**Comment by iruzevic** [comment]
we can merge this if everything is ok and discus future improvements on WP Standup

**Comment by IvanGrginovInf** [comment]
@dingo-d thanks for looking at this.

## Ugly cards
> Love the structure, the only issue I have is the 100px border-radius on the cards and the huge 'pop up' effect on hover.
> Just looks... well... kinda ugly :S
> 
> Maybe something less bordered with a less yellow background? Something like:
> 
> example

I kinda agree, it doesn't work as well when things are this large. The reasoning is that Ive based all things on [https://eightshift.com](https://eightshift.com)'s design / styleguide. This is how buttons look / appear (although they're not as huge) there (large border radius and the scale on hover).

At first I went with a card design, I'll revert it back to that show you, that should work much better for such large "buttons".

## Colors
> Make it as 'clean' as possible no need to go overboard with tons of different colors. Some inspiration:
> 
> https://dribbble.com/search/documentation

I see your point but hear me out.

IMO I think different bold colors for different things (like on `/getting-started` page) are a great way to differentiate between **many very similar but different things** our Boilerplate does.

Most other documentation sites are very focused and document a single library with a single purpose.

We on the other hand have 2 libraries used by 2 boilerplates and a way to make those 2 libraries work without the boilerplate. Also the documentation for those 2 libraries and some guides. That's complex.

Color coding things at the start of the user's journey is IMO a great way to differentiate between these issues.

_Also Eightshift's design centers around many different bold colors which is where I've got them._

On `/docs`, I agree with the comment, we probably need to incorporate the PHP / JS / SCSS logos a bit better in the buttons (I'd like to keep those, again to better differentiate similar things for new users), this is just what I've put together on a saturday morning, I'm more than open for alternative ideas. 😄

**Comment by dingo-d** [comment]
> IMO I think different bold colors for different things (like on /getting-started page) are a great way to differentiate between many very similar but different things our Boilerplate does.

I get the need for differentiation, but the 100px colored buttons are just plain ugly. Ask people from the design team, I'm sure they'll say the same. The differentiation can be done in a better/prettier way IMO.

> Also Eightshift's design centers around many different bold colors which is where I've got them.

Yeah, but the color combination and the way the docs look differs a ton from the site. The current color combination just doesn't work in the docs.

So either the entire docs should be designed to mimic the site or cleaned up.

Personally, I wouldn't force the site design on the docs. The site's mission and what it conveys is totally different from the documentation. Documentation is aimed at developers. They don't care about flashy colors, more about the structure of the docs and its content.

**Comment by IvanGrginovInf** [comment]
> > IMO I think different bold colors for different things (like on /getting-started page) are a great way to differentiate between many very similar but different things our Boilerplate does.
> 
> I get the need for differentiation, but the 100px eounded colored buttons are just plain ugly. Ask people from the design team, I'm sure they'll say the same. The differentiation can be done in a better/prettier way IMO.
> 
> > Also Eightshift's design centers around many different bold colors which is where I've got them.
> 
> Yeah, but the color combination and the way the docs look differs a ton from the site. The current color combination just doesn't work in the docs.
> 
> So either the entire docs should be designed to mimic the site or cleaned up.
> 
> Personally, I wouldn't force the site design on the docs. The site's mission and what it conveys is totally different from the documentation. 

I'm not a designer, and I have no intention of "designing" the docs, which is why I've used something we already have that I personally think looks nice.

I've tested it without colors and it looked bland AF.

> Documentation is aimed at developers. They don't care about flashy colors, more about the structure of the docs and its content

That's a subjective opinion, I personally like a little color in something that's generally considered bland. Also if I'm not mistaken your blog has many differently colored article cards on homepage - and your blog is also aimed at developers. 🤷‍♂ 

Anyway, I agree about buttons looking ugly and I'll fix that. I don't necessarily agree about the colors - both of these things we can talk about on standup or otherwise IRL.

**Comment by dingo-d** [comment]
> That's a subjective opinion, I personally like a little color in something that's generally considered bland. Also if I'm not mistaken your blog has many differently colored article cards on homepage - and your blog is also aimed at developers

You haven't looked at my site lately I guess xD

**Comment by IvanGrginovInf** [comment]
> > That's a subjective opinion, I personally like a little color in something that's generally considered bland. Also if I'm not mistaken your blog has many differently colored article cards on homepage - and your blog is also aimed at developers
> 
> You haven't looked at my site lately I guess xD

Guess that was some mockup you worked on. Anyway, I looked at it and still found the same thing: https://madebydenis.com/wordpress/

Many very similar things differentiated by color. 😄

**Comment by IvanGrginovInf** [comment]
@dingo-d This should be better (card design rather than large button).

# Cards
Getting stareted - with color

# Cards - no color (added some box shadow)
Getting started - no color

**Comment by dingo-d** [comment]
I like the no color better.

If we go with the color, we need to get designers involved, because the whole color combo doesn't feel nice to me.

**Comment by iruzevic** [comment]
@IvanGrginovInf lets go with no color but put some color on the icon and we can fine tune it later.

**Comment by gabriel-glo** [comment]
Maybe it was just the choice of colors, but I think that there should be no color on the background of the cards. Only thing I would color would be the icons on hover (but with different color choices)

**Comment by iruzevic** [comment]
I will create a new design in sketch so just merge this PR so we can push new docs out

**Comment by IvanGrginovInf** [comment]
Made them white with box shadow for now, removed the scaling on hover.

As for color choices I agree, I just used random Eightshift's colors. I'd say
- Warm colors for "plugin" and "theme" options (because those are "I want to start working" / impulsive choice - for example: orange & red). 
- Cold colors (for example: blue & purple) for docs & custom libs / frontend-libs implementation (because they're the less impulsive / slower / harder choices).

As for chaging the color of icons, I can't easily change that right now because they're implemented as ``). Doing it differently might require an `svg-loader` in webpack config (which we can't modify).

I left them without color for now. @iruzevic please approve and I'll merge.

**Pull request merged**
